# Generated by Django 4.0 on 2022-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijkstra_alg', '0002_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='from_node',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='to_node',
            field=models.IntegerField(),
        ),
    ]
