# Generated by Django 4.0 on 2022-03-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijkstra_alg', '0003_alter_node_from_node_alter_node_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={},
        ),
        migrations.AlterModelTable(
            name='node',
            table=None,
        ),
    ]
