# Generated by Django 4.0 on 2022-03-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijkstra_alg', '0004_alter_node_options_alter_node_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
